[default]
workshop = [
    "450814997",  # CBA_A3
    "2369477168", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
    "463939057", # ACE
    "2743998048", # House Kandossi Aux Mod
]
presets = []
dlc = []
optionals = []
parameters = []