[default]
workshop = [
    "450814997",  # CBA_A3
    "3499977893", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
    "463939057", # ACE
]
presets = []
dlc = []
optionals = []
parameters = []

[photo]
extends = "default"
workshop = [
    "1862880106", # POLPOX's Base Functions
    "1341387001", # POLPOX's Artwork Supporter
    "2776005424"  # Enhanced Artwork Supporter
]